/**
 * Extension de l'Antecede Graph (Module 7) à l'univers d'actifs complet —
 * stocks, ETFs, commodités, bonds, FX, crypto — en plus du dataset défense
 * initial (seed-antecede.ts). Additif : ne touche pas aux 19 entités existantes.
 * Lancer avec : npx tsx prisma/seed-antecede-assets.ts
 */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const nodes = [
  { id: "aapl", name: "Apple", type: "company", ticker: "AAPL" },
  { id: "msft", name: "Microsoft", type: "company", ticker: "MSFT" },
  { id: "nvda", name: "NVIDIA", type: "company", ticker: "NVDA" },
  { id: "googl", name: "Alphabet", type: "company", ticker: "GOOGL" },
  { id: "amzn", name: "Amazon", type: "company", ticker: "AMZN" },
  { id: "meta", name: "Meta Platforms", type: "company", ticker: "META" },
  { id: "tsla", name: "Tesla", type: "company", ticker: "TSLA" },
  { id: "xom", name: "Exxon Mobil", type: "company", ticker: "XOM" },
  { id: "cvx", name: "Chevron", type: "company", ticker: "CVX" },
  { id: "jpm", name: "JPMorgan Chase", type: "company", ticker: "JPM" },
  { id: "gs", name: "Goldman Sachs", type: "company", ticker: "GS" },
  { id: "bac", name: "Bank of America", type: "company", ticker: "BAC" },
  { id: "ba", name: "Boeing", type: "company", ticker: "BA" },
  { id: "cat", name: "Caterpillar", type: "company", ticker: "CAT" },
  { id: "de", name: "Deere", type: "company", ticker: "DE" },
  { id: "pfe", name: "Pfizer", type: "company", ticker: "PFE" },
  { id: "jnj", name: "Johnson & Johnson", type: "company", ticker: "JNJ" },
  { id: "unh", name: "UnitedHealth", type: "company", ticker: "UNH" },
  { id: "wmt", name: "Walmart", type: "company", ticker: "WMT" },
  { id: "cost", name: "Costco", type: "company", ticker: "COST" },
  { id: "ko", name: "Coca-Cola", type: "company", ticker: "KO" },
  { id: "pep", name: "PepsiCo", type: "company", ticker: "PEP" },
  { id: "dis", name: "Disney", type: "company", ticker: "DIS" },
  { id: "nflx", name: "Netflix", type: "company", ticker: "NFLX" },
  { id: "intc", name: "Intel", type: "company", ticker: "INTC" },
  { id: "amd", name: "AMD", type: "company", ticker: "AMD" },
  { id: "shel", name: "Shell", type: "company", ticker: "SHEL" },
  { id: "bp", name: "BP", type: "company", ticker: "BP" },
  { id: "tm", name: "Toyota", type: "company", ticker: "TM" },
  { id: "sony", name: "Sony", type: "company", ticker: "SONY" },
  { id: "baba", name: "Alibaba", type: "company", ticker: "BABA" },
  { id: "nke", name: "Nike", type: "company", ticker: "NKE" },
  { id: "mcd", name: "McDonald's", type: "company", ticker: "MCD" },
  { id: "v", name: "Visa", type: "company", ticker: "V" },
  { id: "ma", name: "Mastercard", type: "company", ticker: "MA" },
  { id: "crm", name: "Salesforce", type: "company", ticker: "CRM" },
  { id: "orcl", name: "Oracle", type: "company", ticker: "ORCL" },
  { id: "ibm", name: "IBM", type: "company", ticker: "IBM" },
  { id: "csco", name: "Cisco", type: "company", ticker: "CSCO" },
  { id: "qcom", name: "Qualcomm", type: "company", ticker: "QCOM" },
  { id: "txn", name: "Texas Instruments", type: "company", ticker: "TXN" },
  { id: "hon", name: "Honeywell", type: "company", ticker: "HON" },
  { id: "ge", name: "General Electric", type: "company", ticker: "GE" },
  { id: "ups", name: "United Parcel Service", type: "company", ticker: "UPS" },
  { id: "fdx", name: "FedEx", type: "company", ticker: "FDX" },
  { id: "soxx", name: "iShares Semiconductor ETF", type: "etf", ticker: "SOXX" },
  { id: "spy", name: "SPDR S&P 500 ETF", type: "etf", ticker: "SPY" },
  { id: "qqq", name: "Invesco QQQ", type: "etf", ticker: "QQQ" },
  { id: "dia", name: "SPDR Dow Jones ETF", type: "etf", ticker: "DIA" },
  { id: "iwm", name: "iShares Russell 2000", type: "etf", ticker: "IWM" },
  { id: "xle", name: "Energy Select Sector SPDR", type: "etf", ticker: "XLE" },
  { id: "xlf", name: "Financial Select Sector SPDR", type: "etf", ticker: "XLF" },
  { id: "xlk", name: "Technology Select Sector SPDR", type: "etf", ticker: "XLK" },
  { id: "xlv", name: "Health Care Select Sector SPDR", type: "etf", ticker: "XLV" },
  { id: "xli", name: "Industrial Select Sector SPDR", type: "etf", ticker: "XLI" },
  { id: "xlb", name: "Materials Select Sector SPDR", type: "etf", ticker: "XLB" },
  { id: "xlu", name: "Utilities Select Sector SPDR", type: "etf", ticker: "XLU" },
  { id: "xly", name: "Consumer Discretionary SPDR", type: "etf", ticker: "XLY" },
  { id: "xlp", name: "Consumer Staples SPDR", type: "etf", ticker: "XLP" },
  { id: "xlc", name: "Communication Services SPDR", type: "etf", ticker: "XLC" },
  { id: "xlre", name: "Real Estate Select Sector SPDR", type: "etf", ticker: "XLRE" },
  { id: "gld", name: "SPDR Gold Shares", type: "etf", ticker: "GLD" },
  { id: "slv", name: "iShares Silver Trust", type: "etf", ticker: "SLV" },
  { id: "uso", name: "United States Oil Fund", type: "etf", ticker: "USO" },
  { id: "ung", name: "United States Natural Gas Fund", type: "etf", ticker: "UNG" },
  { id: "dbc", name: "Invesco DB Commodity Index", type: "etf", ticker: "DBC" },
  { id: "tlt", name: "iShares 20+ Year Treasury Bond", type: "etf", ticker: "TLT" },
  { id: "ief", name: "iShares 7-10 Year Treasury Bond", type: "etf", ticker: "IEF" },
  { id: "shy", name: "iShares 1-3 Year Treasury Bond", type: "etf", ticker: "SHY" },
  { id: "hyg", name: "iShares High Yield Corporate Bond", type: "etf", ticker: "HYG" },
  { id: "lqd", name: "iShares Investment Grade Corporate Bond", type: "etf", ticker: "LQD" },
  { id: "eem", name: "iShares MSCI Emerging Markets", type: "etf", ticker: "EEM" },
  { id: "efa", name: "iShares MSCI EAFE", type: "etf", ticker: "EFA" },
  { id: "vxx", name: "iPath VIX Short-Term Futures", type: "etf", ticker: "VXX" },
  { id: "ewz", name: "iShares MSCI Brazil", type: "etf", ticker: "EWZ" },
  { id: "cibr", name: "First Trust Cybersecurity", type: "etf", ticker: "CIBR" },
  { id: "ita", name: "iShares US Aerospace & Defense", type: "etf", ticker: "ITA" },
  { id: "hack", name: "ETFMG Prime Cyber Security", type: "etf", ticker: "HACK" },
  { id: "xop", name: "SPDR S&P Oil & Gas Exploration", type: "etf", ticker: "XOP" },
  { id: "emgf", name: "iShares Emerging Markets Factor", type: "etf", ticker: "EMGF" },
  { id: "arkk", name: "ARK Innovation ETF", type: "etf", ticker: "ARKK" },
  { id: "kweb", name: "KraneShares CSI China Internet", type: "etf", ticker: "KWEB" },
  { id: "fxi", name: "iShares China Large-Cap", type: "etf", ticker: "FXI" },
  { id: "natural_gas", name: "Gaz naturel", type: "resource" },
  { id: "copper", name: "Cuivre", type: "resource" },
  { id: "aluminum", name: "Aluminium", type: "resource" },
  { id: "wheat", name: "Blé", type: "resource" },
  { id: "corn", name: "Maïs", type: "resource" },
  { id: "cotton", name: "Coton", type: "resource" },
  { id: "sugar", name: "Sucre", type: "resource" },
  { id: "coffee", name: "Café", type: "resource" },
  { id: "gold", name: "Or", type: "resource" },
  { id: "silver", name: "Argent", type: "resource" },
  { id: "us_3m", name: "US 3-Month Treasury Bill", type: "bond" },
  { id: "us_2y", name: "US 2-Year Treasury Note", type: "bond" },
  { id: "us_5y", name: "US 5-Year Treasury Note", type: "bond" },
  { id: "us_7y", name: "US 7-Year Treasury Note", type: "bond" },
  { id: "us_10y", name: "US 10-Year Treasury Note", type: "bond" },
  { id: "us_30y", name: "US 30-Year Treasury Bond", type: "bond" },
  { id: "eur_usd", name: "EUR/USD", type: "currency", ticker: "EURUSD" },
  { id: "usd_jpy", name: "USD/JPY", type: "currency", ticker: "USDJPY" },
  { id: "gbp_usd", name: "GBP/USD", type: "currency", ticker: "GBPUSD" },
  { id: "usd_cny", name: "USD/CNY", type: "currency", ticker: "USDCNY" },
  { id: "usd_chf", name: "USD/CHF", type: "currency", ticker: "USDCHF" },
  { id: "aud_usd", name: "AUD/USD", type: "currency", ticker: "AUDUSD" },
  { id: "usd_cad", name: "USD/CAD", type: "currency", ticker: "USDCAD" },
  { id: "bitcoin", name: "Bitcoin", type: "crypto", ticker: "BTC" },
  { id: "ethereum", name: "Ethereum", type: "crypto", ticker: "ETH" },
  { id: "solana", name: "Solana", type: "crypto", ticker: "SOL" },
  { id: "xrp", name: "XRP", type: "crypto", ticker: "XRP" },
  { id: "japan", name: "Japon", type: "country" },
  { id: "eurozone", name: "Zone Euro", type: "country" },
  { id: "uk", name: "Royaume-Uni", type: "country" },
  { id: "switzerland", name: "Suisse", type: "country" },
  { id: "australia", name: "Australie", type: "country" },
  { id: "canada", name: "Canada", type: "country" },
  { id: "brazil", name: "Brésil", type: "country" },
];

const edges: {
  sourceId: string; targetId: string; edgeType: string; edgeCategory: string;
  weightFinancialPct?: number; direction?: string; status?: string; confidence?: string; chokepointType?: string; note?: string;
}[] = [
  { sourceId: "xlk", targetId: "spy", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "medium", note: "Poids sectoriel dans le S&P 500." },
  { sourceId: "aapl", targetId: "xlk", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "msft", targetId: "xlk", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "nvda", targetId: "xlk", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "intc", targetId: "xlk", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "amd", targetId: "xlk", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "orcl", targetId: "xlk", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "ibm", targetId: "xlk", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "csco", targetId: "xlk", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "qcom", targetId: "xlk", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "txn", targetId: "xlk", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "crm", targetId: "xlk", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "xlc", targetId: "spy", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "medium", note: "Poids sectoriel dans le S&P 500." },
  { sourceId: "googl", targetId: "xlc", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "meta", targetId: "xlc", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "dis", targetId: "xlc", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "nflx", targetId: "xlc", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "xly", targetId: "spy", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "medium", note: "Poids sectoriel dans le S&P 500." },
  { sourceId: "amzn", targetId: "xly", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "tsla", targetId: "xly", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "nke", targetId: "xly", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "mcd", targetId: "xly", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "xle", targetId: "spy", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "medium", note: "Poids sectoriel dans le S&P 500." },
  { sourceId: "xom", targetId: "xle", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "cvx", targetId: "xle", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "shel", targetId: "xle", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "bp", targetId: "xle", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "xlf", targetId: "spy", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "medium", note: "Poids sectoriel dans le S&P 500." },
  { sourceId: "jpm", targetId: "xlf", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "gs", targetId: "xlf", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "bac", targetId: "xlf", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "v", targetId: "xlf", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "ma", targetId: "xlf", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "xlv", targetId: "spy", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "medium", note: "Poids sectoriel dans le S&P 500." },
  { sourceId: "pfe", targetId: "xlv", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "jnj", targetId: "xlv", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "unh", targetId: "xlv", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "xli", targetId: "spy", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "medium", note: "Poids sectoriel dans le S&P 500." },
  { sourceId: "lmt", targetId: "xli", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "rtx", targetId: "xli", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "noc", targetId: "xli", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "ba", targetId: "xli", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "cat", targetId: "xli", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "de", targetId: "xli", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "hon", targetId: "xli", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "ge", targetId: "xli", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "ups", targetId: "xli", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "fdx", targetId: "xli", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "xlp", targetId: "spy", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "medium", note: "Poids sectoriel dans le S&P 500." },
  { sourceId: "wmt", targetId: "xlp", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "cost", targetId: "xlp", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "ko", targetId: "xlp", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "pep", targetId: "xlp", edgeType: "component_of", edgeCategory: "trade", weightFinancialPct: 5, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "nvda", targetId: "semiconductors", edgeType: "designs", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "amd", targetId: "semiconductors", edgeType: "designs", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "qcom", targetId: "semiconductors", edgeType: "designs", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "txn", targetId: "semiconductors", edgeType: "designs", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "intc", targetId: "semiconductors", edgeType: "produces", edgeCategory: "trade", weightFinancialPct: 15, direction: "positive", status: "active", confidence: "high", note: "Un des rares IDM occidentaux (design + fab)." },
  { sourceId: "soxx", targetId: "semiconductors", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 40, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "soxx", targetId: "taiwan", edgeType: "concentration_risk", edgeCategory: "dependency", weightFinancialPct: 30, direction: "negative", status: "active", confidence: "high", chokepointType: "taiwan_strait", note: "SOXX fortement exposé à TSMC — risque de concentration géographique." },
  { sourceId: "xom", targetId: "crude_oil", edgeType: "produces", edgeCategory: "trade", weightFinancialPct: 30, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "cvx", targetId: "crude_oil", edgeType: "produces", edgeCategory: "trade", weightFinancialPct: 30, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "shel", targetId: "crude_oil", edgeType: "produces", edgeCategory: "trade", weightFinancialPct: 30, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "bp", targetId: "crude_oil", edgeType: "produces", edgeCategory: "trade", weightFinancialPct: 30, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "xle", targetId: "crude_oil", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 35, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "xop", targetId: "crude_oil", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 40, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "uso", targetId: "crude_oil", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 90, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "dbc", targetId: "crude_oil", edgeType: "tracks", edgeCategory: "dependency", weightFinancialPct: 20, direction: "positive", status: "active", confidence: "medium", note: "Panier de commodités, pétrole = composante majeure." },
  { sourceId: "ung", targetId: "natural_gas", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 90, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "natural_gas", targetId: "russia", edgeType: "exports", edgeCategory: "trade", weightFinancialPct: 25, direction: "positive", status: "active", confidence: "high", note: "Russie parmi les premiers exportateurs mondiaux de gaz naturel." },
  { sourceId: "natural_gas", targetId: "usa", edgeType: "produces", edgeCategory: "trade", weightFinancialPct: 30, direction: "positive", status: "active", confidence: "high", note: "Boom du GNL américain (Gulf Coast export terminals)." },
  { sourceId: "wheat", targetId: "ukraine", edgeType: "exports", edgeCategory: "trade", weightFinancialPct: 40, direction: "positive", status: "active", confidence: "high", note: "Corridor céréalier mer Noire — ~10% des exports mondiaux de blé." },
  { sourceId: "wheat", targetId: "russia", edgeType: "exports", edgeCategory: "trade", weightFinancialPct: 35, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "corn", targetId: "ukraine", edgeType: "exports", edgeCategory: "trade", weightFinancialPct: 30, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "de", targetId: "wheat", edgeType: "demand_correlated", edgeCategory: "dependency", weightFinancialPct: 15, direction: "positive", status: "active", confidence: "medium", note: "Revenus agricoles (prix des céréales) influencent la demande d'équipement Deere." },
  { sourceId: "de", targetId: "corn", edgeType: "demand_correlated", edgeCategory: "dependency", weightFinancialPct: 15, direction: "positive", status: "active", confidence: "medium" },
  { sourceId: "copper", targetId: "china", edgeType: "imports", edgeCategory: "dependency", weightFinancialPct: 50, direction: "positive", status: "active", confidence: "high", note: "Chine = ~50% de la demande mondiale de cuivre raffiné." },
  { sourceId: "aluminum", targetId: "china", edgeType: "imports", edgeCategory: "dependency", weightFinancialPct: 45, direction: "positive", status: "active", confidence: "high", note: "Chine = premier producteur et consommateur mondial d'aluminium." },
  { sourceId: "gld", targetId: "gold", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 95, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "slv", targetId: "silver", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 95, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "coffee", targetId: "brazil", edgeType: "exports", edgeCategory: "trade", weightFinancialPct: 35, direction: "positive", status: "active", confidence: "high", note: "Brésil = premier exportateur mondial de café." },
  { sourceId: "sugar", targetId: "brazil", edgeType: "exports", edgeCategory: "trade", weightFinancialPct: 40, direction: "positive", status: "active", confidence: "high", note: "Brésil = premier exportateur mondial de sucre." },
  { sourceId: "us_3m", targetId: "usa", edgeType: "issued_by", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "us_2y", targetId: "usa", edgeType: "issued_by", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "us_5y", targetId: "usa", edgeType: "issued_by", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "us_7y", targetId: "usa", edgeType: "issued_by", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "us_10y", targetId: "usa", edgeType: "issued_by", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "us_30y", targetId: "usa", edgeType: "issued_by", edgeCategory: "trade", weightFinancialPct: 10, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "tlt", targetId: "us_30y", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 90, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "ief", targetId: "us_10y", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 90, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "shy", targetId: "us_2y", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 90, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "hyg", targetId: "usa", edgeType: "credit_exposure", edgeCategory: "dependency", weightFinancialPct: 15, direction: "positive", status: "active", confidence: "medium", note: "Corporate high-yield — sensible au cycle de crédit US." },
  { sourceId: "lqd", targetId: "usa", edgeType: "credit_exposure", edgeCategory: "dependency", weightFinancialPct: 15, direction: "positive", status: "active", confidence: "medium" },
  { sourceId: "eur_usd", targetId: "eurozone", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 50, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "usd_jpy", targetId: "japan", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 50, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "gbp_usd", targetId: "uk", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 50, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "usd_cny", targetId: "china", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 50, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "usd_chf", targetId: "switzerland", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 50, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "aud_usd", targetId: "australia", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 50, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "usd_cad", targetId: "canada", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 50, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "bitcoin", targetId: "usa", edgeType: "regulatory_exposure", edgeCategory: "dependency", weightFinancialPct: 10, direction: "negative", status: "active", confidence: "medium", note: "Soumis à la surveillance réglementaire SEC/CFTC." },
  { sourceId: "ethereum", targetId: "usa", edgeType: "regulatory_exposure", edgeCategory: "dependency", weightFinancialPct: 10, direction: "negative", status: "active", confidence: "medium", note: "Soumis à la surveillance réglementaire SEC/CFTC." },
  { sourceId: "solana", targetId: "usa", edgeType: "regulatory_exposure", edgeCategory: "dependency", weightFinancialPct: 10, direction: "negative", status: "active", confidence: "medium", note: "Soumis à la surveillance réglementaire SEC/CFTC." },
  { sourceId: "xrp", targetId: "usa", edgeType: "regulatory_exposure", edgeCategory: "dependency", weightFinancialPct: 10, direction: "negative", status: "active", confidence: "medium", note: "Soumis à la surveillance réglementaire SEC/CFTC." },
  { sourceId: "xrp", targetId: "usa", edgeType: "litigation_history", edgeCategory: "conflict", weightFinancialPct: 15, direction: "negative", status: "active", confidence: "high", note: "Contentieux SEC vs Ripple (2020-2023) sur la qualification de titre financier." },
  { sourceId: "tm", targetId: "japan", edgeType: "headquartered_in", edgeCategory: "trade", weightFinancialPct: 60, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "sony", targetId: "japan", edgeType: "headquartered_in", edgeCategory: "trade", weightFinancialPct: 60, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "baba", targetId: "china", edgeType: "headquartered_in", edgeCategory: "trade", weightFinancialPct: 60, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "ewz", targetId: "brazil", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 90, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "kweb", targetId: "china", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 85, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "fxi", targetId: "china", edgeType: "tracks", edgeCategory: "trade", weightFinancialPct: 90, direction: "positive", status: "active", confidence: "verified" },
  { sourceId: "ita", targetId: "lmt", edgeType: "holds", edgeCategory: "trade", weightFinancialPct: 15, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "ita", targetId: "rtx", edgeType: "holds", edgeCategory: "trade", weightFinancialPct: 15, direction: "positive", status: "active", confidence: "high" },
  { sourceId: "ita", targetId: "noc", edgeType: "holds", edgeCategory: "trade", weightFinancialPct: 15, direction: "positive", status: "active", confidence: "high" },
];

async function main() {
  for (const n of nodes) {
    await prisma.antecedeNode.upsert({
      where: { id: n.id },
      update: {},
      create: n,
    });
  }

  for (const e of edges) {
    const exists = await prisma.antecedeEdge.findFirst({
      where: { sourceId: e.sourceId, targetId: e.targetId, edgeType: e.edgeType },
    });
    if (!exists) {
      await prisma.antecedeEdge.create({ data: e });
    }
  }

  console.log(`Seeded ${nodes.length} nodes and ${edges.length} edges (asset universe extension).`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
